README.md

@ThetaShis 
レビューお願いします。
Whitepaperのリンクの変更の修正です。

fix: whitepaper link

---

validators/mainnet-upgrades.md
validators/setting-cosmovisor.md

A page for the description about network upgrade.

add doc about upgrades

---

SUMMARY.md

I didn't modify the SUMMARY.md to publish the added page for the gitbook.
Sorry for the inconvenience, plz review and merge, @mkXultra .

fix to expose upgrades page

---

SUMMARY.md
cli/cli-introduction.md
cli/modules/README.md
cli/modules/nftmarket.md
cli/modules/nftmint.md
cli/ununifid-cli-commands.md

- Added CLI documentation for developers
- nftmint
- nftmarket

feat: add nftmint, nftmarket document

---

README.md
bubble/how-to-use-application-plugin.md
bubble/how-to-use-separated-plugin.md

The document for ununifi's bubble plugins.
How to use for bubble developers.

Bubble Plugin Document

---

README.md
SUMMARY.md

feat: summary

---

SUMMARY.md
bubble/how-to-use-application-plugin.md
bubble/how-to-use-separated-plugin.md

chore: text some fix

---

README.md
SUMMARY.md
cli/cli-introduction.md
cli/modules/README.md
cli/modules/derivatives.md
cli/modules/nftmarket.md
cli/modules/nftmint.md
cli/modules/yield-aggregator.md
develop/faq.md
develop/frontend.md
develop/resources.md
develop/strategy.md
develop/tools.md
develop/tools/cosmos-client.md
validators/ununifid-installation-and-setup.md

Add Developer tool reference
- CLI
- Derivatives
- Yield Aggregator
- cosmos-client
- Ecosystem Incentive
- Resources (LCD, Testnet)

feat: developer tool info 

---

SUMMARY.md
node/types/consensus/genesis-validator.md
node/types/consensus/validator-node.md

Add validator document (before genesis)
**Issue number** - linked number
**Discord-userId** - example#0000   
**UnUniFi-walletAddress** - ununifi1example~

feat: genesis-validator

---

learn/optimism/sunrise-op-stack.md
learn/sunrise/swap.md

Greatly expanded swap page details with diagram and explanation, matches Japanese docs more closely.
**Issue number** - linked number
**Discord-userId** - example#0000  
**UnUniFi-walletAddress** - ununifi1example~

add:expanded details and diagrams

---

learn/sunrise/data-availability.md

add:refactor

---

learn/sunrise/data-availability.md
learn/sunrise/proof-of-liquidity.md

fix:Rise typo

---

learn/sunrise/fee.md

add: paramter info

---

learn/sunrise/fee.md

lint and default parameters fix

---

SUMMARY.md
build/l2-blockchains/README.md
build/l2-blockchains/op-da-server.md
build/l2-blockchains/rollkit.md
build/l2-blockchains/sunrise-data.md

**Issue number** - linked number
**Discord-userId** - example#0000   
**UnUniFi-walletAddress** - ununifi1example~

feat: Rollkit support

---

SUMMARY.md
build/l2-blockchains/sunrise-data.md
build/validators/README.md
build/validators/data-availability-proof.md
build/validators/self-delegation.md
learn/sunrise/data-availability.md
learn/sunrise/lockup-account.md

Validator doc update

---

node/types/consensus/validator-node.md

- add: Validator public key
- fix: minimum stake amount to 1 vrise(1000000uvirse)

fix: create validator

---

learn/rise/README.md
learn/sunrise/fee.md
learn/sunrise/liquidity-incentive.md

feat: add docs for liquidity incentive and fee module

---

learn/sunrise/da-fee-abstraction.md
learn/sunrise/token-converter.md

fix: notation of vRISE

---

README.md

feat: add feature request link

---

README.md

fix: make the link clickable

---

learn/sunrise/da-fee-abstraction.md
learn/sunrise/fee.md
learn/sunrise/gauges-voting.md
learn/sunrise/liquidity-pool.md
learn/sunrise/swap.md

feat: add labels

---

learn/sunrise/token-converter.md

feat: add label

---

learn/sunrise/da-fee-abstraction.md
learn/sunrise/fee.md
learn/sunrise/gauges-voting.md
learn/sunrise/liquidity-incentive.md
learn/sunrise/liquidity-pool.md
learn/sunrise/swap.md
learn/sunrise/token-converter.md

feat: make the label for intiutive

---

book.json
learn/sunrise/fee.md
website.css

feat: add colour to tags

---

GITBOOK_SETUP.md
ja/GITBOOK_SETUP.md

Since GitBook's official development has ended, this document provides guidance on handling common installation issues.

Add GITBOOK_SETUP.md with installation troubleshooting guide

---

learn/sunrise/da-fee-abstraction.md
learn/sunrise/gauges-voting.md
learn/sunrise/proof-of-liquidity.md
learn/sunrise/swap.md
learn/sunrise/token-converter.md

feat: enhance the docs

---

SUMMARY.md
learn/sunrise/bribes.md
learn/sunrise/data-availability.md
learn/sunrise/fee-abstraction.md
learn/sunrise/fee.md
learn/sunrise/gauges-voting.md
learn/sunrise/liquidity-incentive.md
learn/sunrise/liquidity-pool.md
learn/sunrise/lockup-account.md
learn/sunrise/proof-of-liquidity.md
learn/sunrise/swap.md
learn/sunrise/token-converter.md

feat: change DA Fee Abstraction and level

---

learn/sunrise/bribes.md
learn/sunrise/da-fee-abstraction.md
learn/sunrise/gauges-voting.md
learn/sunrise/liquidity-incentive.md
learn/sunrise/liquidity-pool.md
learn/sunrise/proof-of-liquidity.md
learn/sunrise/swap.md
learn/sunrise/token-converter.md

feat: changes based on level

---

SUMMARY.md
learn/sunrise/fee.md
learn/sunrise/proof-of-liquidity.md
learn/sunrise/stable.md
learn/usdrise/README.md

- Overview of USDRise (New)
https://github.com/sunriselayer/gitbook/tree/usdrise/learn/usdrise
- Stable Module (New)
https://github.com/sunriselayer/gitbook/blob/usdrise/learn/sunrise/stable.md
- Fee Module (Changed)
https://github.com/sunriselayer/gitbook/blob/usdrise/learn/sunrise/fee.md 
https://github.com/sunriselayer/gitbook/blob/usdrise/learn/sunrise/proof-of-liquidity.md#economic-alignment (fee denom)

feat: add USDRise docments
